### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by shpoongle** [boxdot/gurk-rs#179]
Install is failing using cargo.

> error: failed to compile `gurk v0.2.5-dev (https://github.com/boxdot/gurk-rs#d5e6ffd8)`, intermediate artifacts can be found at `/tmp/cargo-installjtIMEQ`

Caused by:
  failed to select a version for the requirement `curve25519-dalek = "^2.0.0"`
  candidate versions found which didn't match: 3.2.1
  location searched: Git repository https://github.com/signalapp/curve25519-dalek.git?branch=lizard2
  required by package `zkgroup v0.7.3 (https://github.com/signalapp/zkgroup?tag=v0.7.3#197c382e)`
      ... which satisfies git dependency `zkgroup` of package `libsignal-service v0.1.0 (https://github.com/boxdot/libsignal-service-rs?rev=8be91da2#8be91da2)`
      ... which satisfies git dependency `libsignal-service` of package `presage v0.2.0 (https://github.com/boxdot/presage.git?rev=f908e8f#f908e8ff)`
      ... which satisfies git dependency `presage` of package `gurk v0.2.5-dev (/home/linuxuser/.cargo/git/checkouts/gurk-rs-7cf8dc9d9ee78b42/d5e6ffd)`

Excellent project by the way. Although now  (last week or so) sending messages is failing ..

**Comment by boxdot** [comment]
Did you use `cargo install --locked`? Without the locked parameter the Cargo.lock is not taken into account. I am working on upgrading presage. This will resolve the issue. However, locking ist still recommended.Am 02.09.2022 20:40 schrieb shpoongle ***@***.***>:
Install is failing using cargo.

error: failed to compile gurk v0.2.5-dev (https://github.com/boxdot/gurk-rs#d5e6ffd8), intermediate artifacts can be found at /tmp/cargo-installjtIMEQ

Caused by:
failed to select a version for the requirement curve25519-dalek = "^2.0.0"
candidate versions found which didn't match: 3.2.1
location searched: Git repository https://github.com/signalapp/curve25519-dalek.git?branch=lizard2
required by package zkgroup v0.7.3 (https://github.com/signalapp/zkgroup?tag=v0.7.3#197c382e)
... which satisfies git dependency zkgroup of package libsignal-service v0.1.0 (https://github.com/boxdot/libsignal-service-rs?rev=8be91da2#8be91da2)
... which satisfies git dependency libsignal-service of package presage v0.2.0 (https://github.com/boxdot/presage.git?rev=f908e8f#f908e8ff)
... which satisfies git dependency presage of package gurk v0.2.5-dev (/home/linuxuser/.cargo/git/checkouts/gurk-rs-7cf8dc9d9ee78b42/d5e6ffd)
Excellent project by the way. Although now  (last week or so) sending messages is failing ..

**Comment by shpoongle** [comment]
> Did you use `cargo install --locked`? Without the locked parameter the Cargo.lock is not taken into account. I am working on upgrading presage. 

Hello, thanks for the info :-)

Tried it with --locked, this is the output

> error: failed to select a version for the requirement `iana-time-zone = "=0.1.47"`
candidate versions found which didn't match: 0.1.46, 0.1.45, 0.1.42, ...
location searched: crates.io index
required by package `chrono v0.4.22`
    ... which satisfies dependency `chrono = "=0.4.22"` of package `gurk v0.2.5-dev (/home/linuxuser/.cargo/git/checkouts/gurk-rs-7cf8dc9d9ee78b42/d5e6ffd)`

**Comment by boxdot** [comment]
I can't reproduce it locally on macOS. Will try Linux next.

**Comment by shpoongle** [comment]
Reinstalling Cargo fixed this issue. So all seems to be fine :)
